// Fully synthetic demonstration record. No real citizen, government, or
// department data is used — see /docs/07_SECURITY.md. This record is authored
// to exercise the high-risk path: unexplained asset growth, a lapsed operating
// licence, and travel behaviour inconsistent with declared income.

import type { Citizen } from "../types";

export const vikramSinghChauhan: Citizen = {
  citizenId: "NIR-CIT-104871",
  resolutionConfidence: 0.81,
  status: "Flagged",
  quickSummary:
    "Gurugram logistics proprietor. Property holdings of ₹6.55 crore against declared income of ₹22,00,000. Transport operator licence expired; fleet still active.",
  linkedDepartments: [
    "Identity Authority",
    "Income Tax Department",
    "Land Records Department",
    "Transport Department",
    "Regional Transport Authority",
    "Regional Passport Office",
    "Bureau of Immigration",
    "Banking & Credit Bureau",
    "Ministry of Corporate Affairs",
    "Goods & Services Tax Network",
    "Revenue Department",
  ],

  identity: {
    fullName: "Vikram Singh Chauhan",
    dateOfBirth: "1979-11-03",
    gender: "Male",
    aadhaar: "XXXX XXXX 7710",
    pan: "VSCPC7710M",
    passport: "P4471902",
    drivingLicence: "DL04 20050034521",
    voterId: "HRX7710238",
    rationCard: "HR-GGN-2009-771002",
    abhaId: "31-7710-8842-0193",
    phone: "+91 99XXX XX108",
    email: "v.chauhan@synthetic.example",
    photoInitials: "VC",
  },

  addressIntel: {
    geoConfidence: 0.72,
    current: {
      id: "ADR-104871-C",
      type: "Current",
      line: "House No. 21, Sector 45",
      city: "Gurugram",
      state: "Haryana",
      pincode: "122003",
      fromDate: "2015-06-20",
      source: "Land Records Department",
      geoConfidence: 0.93,
    },
    permanent: {
      id: "ADR-104871-P",
      type: "Permanent",
      line: "Village Pataudi, Tehsil Pataudi",
      city: "Gurugram District",
      state: "Haryana",
      pincode: "122503",
      fromDate: "1979-11-03",
      source: "Revenue Department",
      geoConfidence: 0.68,
    },
    historical: [
      {
        id: "ADR-104871-H1",
        type: "Historical",
        line: "Shop-cum-Flat 3, Old Railway Road",
        city: "Gurugram",
        state: "Haryana",
        pincode: "122001",
        fromDate: "2009-03-01",
        toDate: "2015-06-19",
        source: "Municipal Corporation",
        geoConfidence: 0.61,
      },
      {
        id: "ADR-104871-H2",
        type: "Historical",
        line: "Plot 8, Transport Nagar",
        city: "Delhi",
        state: "Delhi",
        pincode: "110042",
        fromDate: "2004-01-10",
        toDate: "2009-02-25",
        source: "Identity Authority",
        geoConfidence: 0.44,
      },
    ],
  },

  family: {
    householdId: "HH-GGN-122003-2101",
    members: [
      { id: "FAM-104871-1", name: "Pooja Chauhan", relation: "Spouse", age: 44, occupation: "Homemaker", verification: "Verified" },
      { id: "FAM-104871-2", name: "Aditya Chauhan", relation: "Son", age: 19, occupation: "Student", verification: "Verified" },
      { id: "FAM-104871-3", name: "Ranvir Singh Chauhan", relation: "Father", age: 74, occupation: "Retired agriculturist", verification: "Unverified" },
      { id: "FAM-104871-4", name: "Kamla Devi", relation: "Mother", age: 70, occupation: "Homemaker", verification: "Pending Verification" },
    ],
    emergencyContact: {
      name: "Pooja Chauhan",
      relation: "Spouse",
      phone: "+91 99XXX XX771",
    },
  },

  employment: {
    history: [
      { id: "EMP-104871-1", employer: "Chauhan Freight & Logistics", role: "Proprietor", sector: "Logistics", since: "2011-04-01", status: "Active" },
      { id: "EMP-104871-2", employer: "Northern Haulage Co.", role: "Fleet Supervisor", sector: "Logistics", since: "2004-02-10", until: "2011-03-25", status: "Former" },
    ],
    gstRegistrations: [
      { gstin: "06VSCPC7710M1ZR", legalName: "Chauhan Freight & Logistics", state: "Haryana", registeredOn: "2017-07-01", status: "Active", lastFiling: "2024-09-11" },
      { gstin: "06VSCPC7710M2ZQ", legalName: "Pataudi Warehousing Services", state: "Haryana", registeredOn: "2021-03-08", status: "Suspended", lastFiling: "2023-11-20" },
    ],
    directorships: [
      { din: "08841027", company: "Chauhan Logistics Holdings Pvt. Ltd.", cin: "U63030HR2020PTC088410", role: "Managing Director", appointedOn: "2020-08-14", status: "Active" },
      { din: "08841027", company: "Pataudi Coldchain Pvt. Ltd.", cin: "U15490HR2022PTC099213", role: "Director", appointedOn: "2022-05-02", status: "Resigned" },
    ],
  },

  properties: [
    {
      id: "PROP-77002",
      category: "Residential",
      address: "House No. 21, Sector 45, Gurugram",
      surveyOrUnitNo: "Plot 21 / Sector 45",
      areaSqFt: 3600,
      purchaseDate: "2015-05-28",
      registrationDate: "2015-06-20",
      declaredValue: 11200000,
      currentValuation: 15500000,
      ownershipShare: "100%",
      encumbrance: "Clear",
      source: "Land Records Department",
      ownershipHistory: [
        { date: "2015-05-28", event: "Sale deed executed", detail: "Purchased from private seller", value: 11200000 },
        { date: "2015-06-20", event: "Registered", detail: "Sub-Registrar Gurugram-II", value: 11200000 },
      ],
    },
    {
      id: "PROP-77890",
      category: "Commercial",
      address: "Warehouse Unit 7, Sector 68 Industrial Area, Gurugram",
      surveyOrUnitNo: "Unit 7 / IA-68",
      areaSqFt: 18000,
      purchaseDate: "2021-01-22",
      registrationDate: "2021-02-11",
      declaredValue: 32000000,
      currentValuation: 36800000,
      ownershipShare: "100%",
      encumbrance: "Clear",
      source: "Land Records Department",
      ownershipHistory: [
        { date: "2021-01-22", event: "Sale deed executed", detail: "Acquired from Sector 68 Industrial Estate", value: 32000000 },
        { date: "2021-02-11", event: "Registered", detail: "Sub-Registrar Gurugram-III", value: 32000000 },
      ],
    },
    {
      id: "PROP-78341",
      category: "Agricultural Land",
      address: "Khasra No. 112, Pataudi Road, Gurugram District",
      surveyOrUnitNo: "Khasra No. 112",
      areaSqFt: 87120,
      purchaseDate: "2023-10-11",
      registrationDate: "2023-11-05",
      declaredValue: 18000000,
      currentValuation: 19400000,
      ownershipShare: "100%",
      encumbrance: "Under Dispute",
      source: "Land Records Department",
      ownershipHistory: [
        { date: "2023-10-11", event: "Sale deed executed", detail: "Acquired from three co-sharers", value: 18000000 },
        { date: "2023-11-05", event: "Registered", detail: "Sub-Registrar Pataudi", value: 18000000 },
        { date: "2024-02-17", event: "Mutation objected", detail: "Objection filed by a co-sharer; mutation not completed" },
      ],
      dispute: {
        caseNumber: "REV/PTD/2024/00318",
        forum: "Revenue Court, Pataudi",
        subject: "Objection to mutation by a recorded co-sharer",
        filedOn: "2024-02-17",
        status: "Open",
      },
    },
    {
      id: "PROP-79115",
      category: "Government Lease",
      address: "Transport Yard Plot 4, State Logistics Park, Sector 68",
      surveyOrUnitNo: "Yard Plot 4",
      areaSqFt: 9000,
      purchaseDate: "2019-04-01",
      registrationDate: "2019-04-18",
      declaredValue: 0,
      currentValuation: 0,
      ownershipShare: "Leasehold — 15 years",
      encumbrance: "Clear",
      source: "Revenue Department",
      ownershipHistory: [
        { date: "2019-04-18", event: "Lease granted", detail: "State Logistics Park lease, expires 2034-03-31" },
      ],
    },
  ],

  vehicles: [
    {
      id: "VEH-61120",
      category: "Commercial",
      makeModel: "Tata Prima 4928.S (Heavy Goods)",
      registrationNumber: "HR55 AB 1102",
      registeredOn: "2018-03-19",
      fuel: "Diesel",
      insurance: { provider: "Northern General Insurance", policyNumber: "NGI-COM-1102-2024", validTill: "2025-03-18", status: "Active" },
      fitness: { certificateNumber: "FC-HR55-1102", validTill: "2025-03-18", status: "Valid" },
      challans: [
        { id: "CHL-22104", date: "2023-02-11", offence: "Overloading (18% above permitted)", location: "NH-48, Manesar", amount: 20000, status: "Paid" },
        { id: "CHL-23890", date: "2024-05-30", offence: "Operating without valid permit", location: "Kherki Daula Toll", amount: 10000, status: "Pending" },
      ],
      ownershipHistory: [{ date: "2018-03-19", event: "Registered", detail: "Registered to Chauhan Freight & Logistics" }],
    },
    {
      id: "VEH-61121",
      category: "Commercial",
      makeModel: "Ashok Leyland 3520 (Heavy Goods)",
      registrationNumber: "HR55 AB 1103",
      registeredOn: "2020-07-22",
      fuel: "Diesel",
      insurance: { provider: "Northern General Insurance", policyNumber: "NGI-COM-1103-2024", validTill: "2025-07-21", status: "Active" },
      fitness: { certificateNumber: "FC-HR55-1103", validTill: "2024-07-21", status: "Expired" },
      challans: [
        { id: "CHL-24551", date: "2024-08-09", offence: "Fitness certificate expired", location: "Sector 68, Gurugram", amount: 5000, status: "Contested" },
      ],
      ownershipHistory: [{ date: "2020-07-22", event: "Registered", detail: "Fleet expansion — registered to Chauhan Freight & Logistics" }],
    },
    {
      id: "VEH-61980",
      category: "Car",
      makeModel: "Toyota Camry Hybrid",
      registrationNumber: "HR26 CQ 7781",
      registeredOn: "2022-12-01",
      fuel: "Hybrid",
      insurance: { provider: "Capital Assurance", policyNumber: "CAP-MOT-7781-2024", validTill: "2025-11-30", status: "Active" },
      fitness: { certificateNumber: "FC-HR26-7781", validTill: "2037-11-30", status: "Valid" },
      challans: [],
      ownershipHistory: [{ date: "2022-12-01", event: "Registered", detail: "Personal vehicle, first owner" }],
    },
    {
      id: "VEH-62210",
      category: "Motorcycle",
      makeModel: "Royal Enfield Classic 350",
      registrationNumber: "HR26 AZ 4410",
      registeredOn: "2016-09-14",
      fuel: "Petrol",
      insurance: { provider: "Capital Assurance", policyNumber: "CAP-MOT-4410-2023", validTill: "2024-09-13", status: "Expired" },
      fitness: { certificateNumber: "FC-HR26-4410", validTill: "2031-09-13", status: "Valid" },
      challans: [],
      ownershipHistory: [{ date: "2016-09-14", event: "Registered", detail: "First owner registration, RTO Gurugram" }],
    },
  ],

  financial: {
    incomeRange: "₹18,00,000 – ₹22,00,000 per annum",
    incomeTax: [
      { assessmentYear: "2024-25", declaredIncome: 2200000, taxPaid: 398000, filingStatus: "Under Review", filedOn: "2024-10-28" },
      { assessmentYear: "2023-24", declaredIncome: 1980000, taxPaid: 341000, filingStatus: "Filed", filedOn: "2023-08-02" },
      { assessmentYear: "2022-23", declaredIncome: 1750000, taxPaid: 0, filingStatus: "Overdue" },
    ],
    bankAccounts: [
      { id: "ACC-1", bank: "Northern Commercial Bank", maskedNumber: "XXXXXXXX7710", type: "Current", branch: "Sector 44, Gurugram", openedOn: "2011-04-12", status: "Active" },
      { id: "ACC-2", bank: "Northern Commercial Bank", maskedNumber: "XXXXXXXX1102", type: "Savings", branch: "Sector 44, Gurugram", openedOn: "2011-04-12", status: "Active" },
      { id: "ACC-3", bank: "Capital Urban Bank", maskedNumber: "XXXXXXXX9928", type: "Current", branch: "Pataudi", openedOn: "2021-02-25", status: "Active" },
    ],
    loans: [
      { id: "LON-1", lender: "Northern Commercial Bank", type: "Commercial Vehicle Loan", sanctionedAmount: 4800000, outstanding: 1120000, emi: 88000, sanctionedOn: "2018-03-02", status: "Active" },
      { id: "LON-2", lender: "Capital Urban Bank", type: "Working Capital", sanctionedAmount: 6000000, outstanding: 5410000, emi: 121000, sanctionedOn: "2021-03-15", status: "Irregular" },
    ],
    creditProfile: { score: 618, bureau: "National Credit Bureau", band: "Fair", asOf: "2025-01-31" },
    mutualFunds: [],
    fixedDeposits: [
      { id: "FD-1", kind: "Fixed Deposit", institution: "Capital Urban Bank", identifier: "FD-9928-0044", value: 2500000, startedOn: "2023-12-04", maturityOn: "2026-12-04" },
    ],
    insurance: [
      { id: "INS-1", insurer: "Northern General Insurance", type: "Vehicle", policyNumber: "NGI-COM-1102-2024", sumAssured: 3200000, annualPremium: 84000, validTill: "2025-03-18", status: "Active" },
      { id: "INS-2", insurer: "Bharat Life Assurance", type: "Life", policyNumber: "BLA-7710-2201", sumAssured: 5000000, annualPremium: 41000, validTill: "2039-12-31", status: "Lapsed" },
    ],
    upiIds: [
      { handle: "chauhanfreight@synthpay", linkedBank: "Northern Commercial Bank", status: "Active" },
      { handle: "vikram.sc@synthbank", linkedBank: "Capital Urban Bank", status: "Active" },
    ],
  },

  travel: {
    passport: {
      number: "P4471902",
      issueDate: "2019-08-22",
      expiryDate: "2029-08-21",
      issuingOffice: "Regional Passport Office, Gurugram",
      status: "Active",
    },
    trips: [
      { id: "TRP-1", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2019-10-04", entryDate: "2019-10-08", durationDays: 4, port: "Delhi (DEL)" },
      { id: "TRP-2", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2020-01-17", entryDate: "2020-01-20", durationDays: 3, port: "Delhi (DEL)" },
      { id: "TRP-3", country: "Singapore", flag: "🇸🇬", purpose: "Business", visaType: "Business (30 days)", exitDate: "2022-03-11", entryDate: "2022-03-16", durationDays: 5, port: "Delhi (DEL)" },
      { id: "TRP-4", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2022-07-29", entryDate: "2022-08-01", durationDays: 3, port: "Delhi (DEL)" },
      { id: "TRP-5", country: "Thailand", flag: "🇹🇭", purpose: "Tourism", visaType: "Visa on Arrival", exitDate: "2022-11-18", entryDate: "2022-11-23", durationDays: 5, port: "Delhi (DEL)" },
      { id: "TRP-6", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2023-02-09", entryDate: "2023-02-13", durationDays: 4, port: "Delhi (DEL)" },
      { id: "TRP-7", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2023-06-22", entryDate: "2023-06-25", durationDays: 3, port: "Delhi (DEL)" },
      { id: "TRP-8", country: "Hong Kong SAR", flag: "🇭🇰", purpose: "Business", visaType: "Pre-arrival Registration", exitDate: "2023-09-14", entryDate: "2023-09-19", durationDays: 5, port: "Delhi (DEL)" },
      { id: "TRP-9", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2023-12-07", entryDate: "2023-12-11", durationDays: 4, port: "Delhi (DEL)" },
      { id: "TRP-10", country: "Singapore", flag: "🇸🇬", purpose: "Business", visaType: "Business (30 days)", exitDate: "2024-04-18", entryDate: "2024-04-22", durationDays: 4, port: "Delhi (DEL)" },
      { id: "TRP-11", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Business", visaType: "Visit (30 days)", exitDate: "2024-09-26", entryDate: "2024-09-30", durationDays: 4, port: "Delhi (DEL)" },
    ],
    immigrationRecords: [
      { id: "IMM-1", date: "2024-09-30", type: "Arrival", port: "Delhi (DEL)", reference: "BOI/ARR/2024/771088", status: "Cleared" },
      { id: "IMM-2", date: "2024-09-26", type: "Departure", port: "Delhi (DEL)", reference: "BOI/DEP/2024/771041", status: "Flagged" },
      { id: "IMM-3", date: "2024-04-22", type: "Arrival", port: "Delhi (DEL)", reference: "BOI/ARR/2024/662190", status: "Cleared" },
      { id: "IMM-4", date: "2024-04-18", type: "Departure", port: "Delhi (DEL)", reference: "BOI/DEP/2024/662055", status: "Cleared" },
      { id: "IMM-5", date: "2023-12-11", type: "Arrival", port: "Delhi (DEL)", reference: "BOI/ARR/2023/551903", status: "Cleared" },
    ],
    totalTrips: 11,
    countriesVisited: 5,
    averageStayDays: 4.0,
    travelFrequency: "≈2.2 trips per year since 2019, 7 to a single destination",
    lastExit: "2024-09-26",
    lastEntry: "2024-09-30",
    observation: {
      text: "Travel pattern is inconsistent with declared income. Eleven international trips in five years — seven to the same destination, average stay 4.0 days — against a declared annual income of ₹22,00,000 and no recorded foreign business entity. One departure in September 2024 carries a flagged immigration status.",
      evidenceIds: ["EV-IM-01", "EV-IM-02", "EV-IT-01", "EV-MCA-01"],
    },
  },

  benefits: [
    { id: "BEN-40011", scheme: "Pradhan Mantri Awas Yojana", category: "Housing", department: "Welfare Department", status: "Not Enrolled", eligibility: "Not Eligible" },
    { id: "BEN-40012", scheme: "Ayushman Bharat", category: "Health", department: "Health Authority", status: "Not Enrolled", eligibility: "Not Eligible" },
    { id: "BEN-40013", scheme: "PM Kisan Samman Nidhi", category: "Agriculture", department: "Welfare Department", enrollmentDate: "2024-01-12", status: "Active", eligibility: "Under Review", amountDisbursed: 6000, lastDisbursedOn: "2024-08-01" },
    { id: "BEN-40014", scheme: "National Pension Scheme", category: "Pension", department: "Welfare Department", status: "Not Enrolled", eligibility: "Eligible" },
    { id: "BEN-40015", scheme: "Direct Benefit Transfer (LPG Subsidy)", category: "DBT", department: "Welfare Department", enrollmentDate: "2014-05-20", status: "Inactive", eligibility: "Not Eligible", amountDisbursed: 7240, lastDisbursedOn: "2019-11-04" },
  ],

  documents: [
    { id: "DOC-81020", type: "Aadhaar", documentNumber: "XXXX XXXX 7710", issuingAuthority: "Identity Authority", issueDate: "2012-09-04", status: "Verified", verificationConfidence: 0.97 },
    { id: "DOC-81021", type: "PAN Card", documentNumber: "VSCPC7710M", issuingAuthority: "Income Tax Department", issueDate: "2004-01-19", status: "Verified", verificationConfidence: 0.98 },
    { id: "DOC-81022", type: "Business Registration Certificate", documentNumber: "MCA/HR/2011/044120", issuingAuthority: "Ministry of Corporate Affairs", issueDate: "2011-04-01", status: "Verified", verificationConfidence: 0.94 },
    { id: "DOC-81023", type: "Income Certificate", documentNumber: "REV/HR/2023/81023", issuingAuthority: "Revenue Department", issueDate: "2023-05-14", expiryDate: "2024-05-13", status: "Unverified", verificationConfidence: 0.31 },
    { id: "DOC-81024", type: "Passport", documentNumber: "P4471902", issuingAuthority: "Regional Passport Office, Gurugram", issueDate: "2019-08-22", expiryDate: "2029-08-21", status: "Verified", verificationConfidence: 0.96 },
    { id: "DOC-81025", type: "Land Mutation Extract", documentNumber: "REV/PTD/2024/00318", issuingAuthority: "Revenue Department", issueDate: "2024-02-17", status: "Disputed", verificationConfidence: 0.22 },
  ],

  licences: [
    { id: "LIC-51002", type: "Transport Operator Licence", category: "Transport", licenceNumber: "RTA/HR/2011/51002", issuingAuthority: "Regional Transport Authority", issueDate: "2011-05-01", expiryDate: "2024-04-30", status: "Expired" },
    { id: "LIC-51003", type: "Driving Licence (HMV)", category: "Driving", licenceNumber: "DL04 20050034521", issuingAuthority: "Regional Transport Authority", issueDate: "2005-02-17", expiryDate: "2025-02-16", status: "Active" },
    { id: "LIC-51004", type: "Goods Carriage Permit (National)", category: "Transport", licenceNumber: "RTA/HR/NP/2019/1102", issuingAuthority: "Regional Transport Authority", issueDate: "2019-06-01", expiryDate: "2024-05-31", status: "Expired" },
    { id: "LIC-51005", type: "Warehousing Operator Registration", category: "Business", licenceNumber: "REV/HR/WH/2021/7789", issuingAuthority: "Revenue Department", issueDate: "2021-03-08", expiryDate: "2026-03-07", status: "Active" },
  ],

  timeline: [
    { date: "2004-01-19", title: "PAN issued", description: "Permanent Account Number allotted.", department: "Income Tax Department", category: "Identity", evidenceIds: ["EV-ID-01"] },
    { date: "2005-02-17", title: "Heavy vehicle driving licence issued", description: "HMV driving licence issued by RTA Haryana.", department: "Regional Transport Authority", category: "Licence", evidenceIds: ["EV-RTA-02"] },
    { date: "2011-04-01", title: "Business registered", description: "Chauhan Freight & Logistics registered as a proprietorship.", department: "Ministry of Corporate Affairs", category: "Employment", evidenceIds: ["EV-MCA-02"] },
    { date: "2011-05-01", title: "Transport operator licence issued", description: "Core operating licence granted, valid to 2024.", department: "Regional Transport Authority", category: "Licence", evidenceIds: ["EV-RTA-01"] },
    { date: "2015-06-20", title: "Residential property registered", description: "Primary residence registered in Sector 45, Gurugram.", department: "Land Records Department", category: "Property", evidenceIds: ["EV-LR-01"] },
    { date: "2018-03-19", title: "First heavy goods vehicle registered", description: "Fleet vehicle registered to the business.", department: "Transport Department", category: "Vehicle", evidenceIds: ["EV-TRD-01"] },
    { date: "2019-08-22", title: "Passport issued", description: "First passport issued by RPO Gurugram.", department: "Regional Passport Office", category: "Travel", evidenceIds: ["EV-PP-01"] },
    { date: "2019-10-04", title: "First international travel", description: "Business travel to the United Arab Emirates.", department: "Bureau of Immigration", category: "Travel", evidenceIds: ["EV-IM-01"] },
    { date: "2020-08-14", title: "Company directorship recorded", description: "Appointed Managing Director of Chauhan Logistics Holdings Pvt. Ltd.", department: "Ministry of Corporate Affairs", category: "Employment", evidenceIds: ["EV-MCA-01"] },
    { date: "2021-02-11", title: "Commercial warehouse registered", description: "Industrial warehouse acquired for ₹3,20,00,000.", department: "Land Records Department", category: "Property", evidenceIds: ["EV-LR-02"] },
    { date: "2022-07-31", title: "FY2022-23 return not filed", description: "Assessment year return recorded as overdue.", department: "Income Tax Department", category: "Financial", evidenceIds: ["EV-IT-02"] },
    { date: "2023-11-05", title: "Agricultural land registered", description: "Land parcel acquired on Pataudi Road for ₹1,80,00,000.", department: "Land Records Department", category: "Property", evidenceIds: ["EV-LR-03"] },
    { date: "2024-02-17", title: "Mutation objection filed", description: "Co-sharer objected to mutation; matter pending before the Revenue Court.", department: "Revenue Department", category: "Property", evidenceIds: ["EV-REV-01"] },
    { date: "2024-04-30", title: "Transport operator licence expired", description: "Core operating licence lapsed with no renewal recorded.", department: "Regional Transport Authority", category: "Licence", evidenceIds: ["EV-RTA-01"] },
    { date: "2024-05-30", title: "Permit violation challan issued", description: "Fleet vehicle cited for operating without a valid permit; challan unpaid.", department: "Transport Department", category: "Vehicle", evidenceIds: ["EV-TRD-02"] },
    { date: "2024-09-26", title: "International departure flagged", description: "Departure to the UAE recorded with a flagged immigration status.", department: "Bureau of Immigration", category: "Travel", evidenceIds: ["EV-IM-02"] },
  ],

  evidence: [
    { id: "EV-ID-01", label: "Core identity record with linked PAN and Aadhaar", sourceDepartment: "Identity Authority", sourceRecordId: "NIR-CIT-104871", referenceNumber: "IDA/GGN/2012/7710", confidence: 0.94, verificationStatus: "Verified", linkedRecord: "Identity → Aadhaar, PAN", recordedOn: "2024-10-11" },
    { id: "EV-IT-01", label: "Income tax return, AY 2024-25 — declared income ₹22,00,000, under review", sourceDepartment: "Income Tax Department", sourceRecordId: "IT-2024-25-2200000", referenceNumber: "ITD/ITR/2024/4471903", confidence: 0.9, verificationStatus: "Pending Verification", linkedRecord: "Financial → Income tax", recordedOn: "2024-10-28" },
    { id: "EV-IT-02", label: "FY2022-23 return recorded as overdue with nil tax paid", sourceDepartment: "Income Tax Department", sourceRecordId: "IT-2022-23-overdue", referenceNumber: "ITD/DEF/2023/104871", confidence: 0.93, verificationStatus: "Verified", linkedRecord: "Financial → Income tax", recordedOn: "2023-04-01" },
    { id: "EV-IT-03", label: "Cumulative declared income FY2021-25 of ₹59,30,000", sourceDepartment: "Income Tax Department", sourceRecordId: "IT-2021-2025-cumulative", referenceNumber: "ITD/HIST/104871", confidence: 0.91, verificationStatus: "Verified", linkedRecord: "Financial → Income tax", recordedOn: "2024-10-28" },
    { id: "EV-LR-01", label: "Residential property registration, Sector 45", sourceDepartment: "Land Records Department", sourceRecordId: "PROP-77002", referenceNumber: "LRD/GGN2/2015/77002", confidence: 0.96, verificationStatus: "Verified", linkedRecord: "Property → PROP-77002", recordedOn: "2015-06-20" },
    { id: "EV-LR-02", label: "Commercial warehouse registration — ₹3,20,00,000", sourceDepartment: "Land Records Department", sourceRecordId: "PROP-77890", referenceNumber: "LRD/GGN3/2021/77890", confidence: 0.95, verificationStatus: "Verified", linkedRecord: "Property → PROP-77890", recordedOn: "2021-02-11" },
    { id: "EV-LR-03", label: "Agricultural land registration — ₹1,80,00,000", sourceDepartment: "Land Records Department", sourceRecordId: "PROP-78341", referenceNumber: "LRD/PTD/2023/78341", confidence: 0.92, verificationStatus: "Verified", linkedRecord: "Property → PROP-78341", recordedOn: "2023-11-05" },
    { id: "EV-REV-01", label: "Open mutation objection before the Revenue Court, Pataudi", sourceDepartment: "Revenue Department", sourceRecordId: "REV/PTD/2024/00318", referenceNumber: "REV/PTD/2024/00318", confidence: 0.87, verificationStatus: "Disputed", linkedRecord: "Property → PROP-78341 dispute", recordedOn: "2024-02-17" },
    { id: "EV-REV-02", label: "Income certificate issued but never verified", sourceDepartment: "Revenue Department", sourceRecordId: "DOC-81023", referenceNumber: "REV/HR/2023/81023", confidence: 0.31, verificationStatus: "Unverified", linkedRecord: "Document → DOC-81023", recordedOn: "2023-05-14" },
    { id: "EV-RTA-01", label: "Transport operator licence expired 30 Apr 2024, no renewal on file", sourceDepartment: "Regional Transport Authority", sourceRecordId: "LIC-51002", referenceNumber: "RTA/HR/2011/51002", confidence: 0.97, verificationStatus: "Verified", linkedRecord: "Licence → LIC-51002", recordedOn: "2024-04-30" },
    { id: "EV-RTA-02", label: "National goods carriage permit expired 31 May 2024", sourceDepartment: "Regional Transport Authority", sourceRecordId: "LIC-51004", referenceNumber: "RTA/HR/NP/2019/1102", confidence: 0.95, verificationStatus: "Verified", linkedRecord: "Licence → LIC-51004", recordedOn: "2024-05-31" },
    { id: "EV-TRD-01", label: "Two heavy goods vehicles still actively registered to the business", sourceDepartment: "Transport Department", sourceRecordId: "VEH-61120, VEH-61121", referenceNumber: "TRD/HR/FLEET/104871", confidence: 0.96, verificationStatus: "Verified", linkedRecord: "Vehicle → VEH-61120, VEH-61121", recordedOn: "2024-08-09" },
    { id: "EV-TRD-02", label: "Unpaid challan for operating without a valid permit", sourceDepartment: "Transport Department", sourceRecordId: "CHL-23890", referenceNumber: "TRD/CHL/2024/23890", confidence: 0.94, verificationStatus: "Verified", linkedRecord: "Vehicle → VEH-61120 challan", recordedOn: "2024-05-30" },
    { id: "EV-TRD-03", label: "Fleet vehicle operating with an expired fitness certificate", sourceDepartment: "Transport Department", sourceRecordId: "VEH-61121", referenceNumber: "TRD/FC/2024/1103", confidence: 0.93, verificationStatus: "Verified", linkedRecord: "Vehicle → VEH-61121 fitness", recordedOn: "2024-07-21" },
    { id: "EV-PP-01", label: "Passport record, active to 2029", sourceDepartment: "Regional Passport Office", sourceRecordId: "DOC-81024", referenceNumber: "RPO/GGN/2019/4471902", confidence: 0.96, verificationStatus: "Verified", linkedRecord: "Travel → Passport", recordedOn: "2019-08-22" },
    { id: "EV-IM-01", label: "Immigration history — 11 trips in 5 years, 7 to a single destination", sourceDepartment: "Bureau of Immigration", sourceRecordId: "IMM-104871-ALL", referenceNumber: "BOI/HIST/104871", confidence: 0.89, verificationStatus: "Verified", linkedRecord: "Travel → Immigration records", recordedOn: "2024-09-30" },
    { id: "EV-IM-02", label: "Flagged departure record, 26 Sep 2024", sourceDepartment: "Bureau of Immigration", sourceRecordId: "IMM-2", referenceNumber: "BOI/DEP/2024/771041", confidence: 0.85, verificationStatus: "Pending Verification", linkedRecord: "Travel → IMM-2", recordedOn: "2024-09-26" },
    { id: "EV-MCA-01", label: "Active managing directorship in a private limited company", sourceDepartment: "Ministry of Corporate Affairs", sourceRecordId: "U63030HR2020PTC088410", referenceNumber: "MCA/DIN/08841027", confidence: 0.93, verificationStatus: "Verified", linkedRecord: "Employment → Directorships", recordedOn: "2024-06-30" },
    { id: "EV-MCA-02", label: "Proprietorship business registration, active since 2011", sourceDepartment: "Ministry of Corporate Affairs", sourceRecordId: "DOC-81022", referenceNumber: "MCA/HR/2011/044120", confidence: 0.94, verificationStatus: "Verified", linkedRecord: "Document → DOC-81022", recordedOn: "2011-04-01" },
    { id: "EV-GST-01", label: "Second GST registration suspended, last filing Nov 2023", sourceDepartment: "Goods & Services Tax Network", sourceRecordId: "06VSCPC7710M2ZQ", referenceNumber: "GST/HR/2021/7710M2", confidence: 0.9, verificationStatus: "Verified", linkedRecord: "Employment → GST", recordedOn: "2023-11-20" },
    { id: "EV-BCB-01", label: "Credit profile — score 618, one irregular working capital facility", sourceDepartment: "Banking & Credit Bureau", sourceRecordId: "CB-104871", referenceNumber: "BCB/RPT/2025/104871", confidence: 0.91, verificationStatus: "Verified", linkedRecord: "Financial → Credit profile", recordedOn: "2025-01-31" },
    { id: "EV-BCB-02", label: "Working capital facility ₹54,10,000 outstanding, marked irregular", sourceDepartment: "Banking & Credit Bureau", sourceRecordId: "LON-2", referenceNumber: "BCB/LON/2021/6000", confidence: 0.9, verificationStatus: "Verified", linkedRecord: "Financial → Loans", recordedOn: "2025-01-31" },
    { id: "EV-ADR-01", label: "Two historical addresses with low geo-match confidence", sourceDepartment: "Identity Authority", sourceRecordId: "ADR-104871-H2", referenceNumber: "IDA/ADR/104871", confidence: 0.44, verificationStatus: "Pending Verification", linkedRecord: "Address → Historical", recordedOn: "2009-02-25" },
  ],

  aiSummary: {
    metrics: {
      aiConfidence: 0.81,
      departmentsCorrelated: 11,
      recordsAnalysed: 79,
      evidenceSources: 23,
      documentsLinked: 6,
      riskScore: 78,
      citizenStatus: "Flagged",
    },
    executiveSummary:
      "Vikram Singh Chauhan is a 45-year-old logistics proprietor in Gurugram, resolved across eleven departments at 81% confidence — the lowest of the resolved records, driven by two historical addresses that could not be corroborated. Property acquisitions of ₹5.00 crore between 2021 and 2023 sit against ₹59,30,000 of cumulative declared income for the same period, with no recorded financing to bridge the gap. The core transport operator licence lapsed in April 2024 while two heavy goods vehicles remain actively registered and in use. International travel is frequent and destination-concentrated in a way the declared income does not explain. Recommended for escalation.",
    domainSummaries: [
      { key: "identity", title: "Identity Summary", text: "Primary identifiers (Aadhaar, PAN, passport, voter ID) are verified and mutually consistent. Resolution confidence is depressed by two historical addresses — a Delhi address from 2004-09 in particular matched at only 44%.", evidenceIds: ["EV-ID-01", "EV-ADR-01"] },
      { key: "income", title: "Income Summary", text: "Declared income across FY2021-25 totals ₹59,30,000. The FY2022-23 return is overdue with nil tax paid, and the FY2024-25 return is under departmental review. An income certificate issued in 2023 was never verified.", evidenceIds: ["EV-IT-01", "EV-IT-02", "EV-IT-03", "EV-REV-02"] },
      { key: "property", title: "Property Summary", text: "Four holdings including a government lease. The 2021 warehouse (₹3,20,00,000) and 2023 land parcel (₹1,80,00,000) together exceed cumulative declared income by roughly ₹4.4 crore. The land parcel carries an open mutation objection before the Revenue Court.", evidenceIds: ["EV-LR-02", "EV-LR-03", "EV-IT-03", "EV-REV-01"] },
      { key: "travel", title: "Travel Summary", text: "Eleven international trips since 2019 with an average stay of 4.0 days, seven of them to the same destination. No foreign business entity is recorded against the citizen or the company that would explain the frequency. One departure carries a flagged immigration status.", evidenceIds: ["EV-IM-01", "EV-IM-02", "EV-MCA-01"] },
      { key: "employment", title: "Employment Summary", text: "Proprietor since 2011 with an active managing directorship from 2020. One of two GST registrations is suspended with no filing since November 2023, while the associated warehousing operation remains registered.", evidenceIds: ["EV-MCA-01", "EV-MCA-02", "EV-GST-01"] },
      { key: "behaviour", title: "Behaviour Summary", text: "A repeating pattern of lapsed statutory obligations: operator licence expired, national permit expired, fitness certificate expired, one challan unpaid and another contested, life insurance lapsed, and a working capital facility marked irregular.", evidenceIds: ["EV-RTA-01", "EV-RTA-02", "EV-TRD-02", "EV-TRD-03", "EV-BCB-02"] },
      { key: "risk", title: "Risk Summary", text: "Risk score 78/100 (High), driven by three independent signals: an unexplained income-to-asset gap, continued commercial operation under an expired licence, and travel behaviour unsupported by declared income.", evidenceIds: ["EV-IT-03", "EV-RTA-01", "EV-TRD-01", "EV-IM-01"] },
    ],
    inconsistencies: [
      { text: "Combined value of the 2021 warehouse and 2023 land acquisition (₹5,00,00,000) exceeds cumulative declared income for the same period (₹59,30,000) by roughly ₹4.4 crore, with no sanctioned facility of that size on record.", evidenceIds: ["EV-LR-02", "EV-LR-03", "EV-IT-03", "EV-BCB-02"] },
      { text: "FY2022-23 tax filing is overdue with nil tax paid, in the year immediately following the largest single asset acquisition.", evidenceIds: ["EV-IT-02", "EV-LR-02"] },
      { text: "Two heavy goods vehicles remain actively registered and challaned on public roads after the transport operator licence and national permit both expired.", evidenceIds: ["EV-RTA-01", "EV-RTA-02", "EV-TRD-01", "EV-TRD-02"] },
      { text: "Travel frequency and destination concentration are not explained by declared income or by any recorded foreign business interest.", evidenceIds: ["EV-IM-01", "EV-IT-03", "EV-MCA-01"] },
    ],
    schemeEligibility: [
      { text: "PM Kisan Samman Nidhi enrolment is Active with a disbursement recorded, but eligibility is Under Review — the underlying landholding is subject to an unresolved mutation objection.", evidenceIds: ["EV-REV-01", "EV-LR-03"] },
      { text: "Not eligible for income-linked or housing schemes given declared income and registered asset holdings.", evidenceIds: ["EV-IT-01", "EV-LR-01"] },
    ],
    linkedEntities: [
      { text: "'Chauhan Freight & Logistics' is the registered owner on both heavy goods vehicle records, confirming an overlap between personal and business assets.", evidenceIds: ["EV-TRD-01", "EV-MCA-02"] },
      { text: "Managing directorship of Chauhan Logistics Holdings Pvt. Ltd. (CIN U63030HR2020PTC088410) was taken up five months before the warehouse acquisition.", evidenceIds: ["EV-MCA-01", "EV-LR-02"] },
      { text: "The suspended GST registration 'Pataudi Warehousing Services' shares its operating address with the Sector 68 warehouse holding.", evidenceIds: ["EV-GST-01", "EV-LR-02"] },
    ],
    investigationLeads: [
      { text: "Reconcile the source of funds for the 2021 and 2023 acquisitions against filed income and sanctioned credit for those years.", evidenceIds: ["EV-LR-02", "EV-LR-03", "EV-IT-03", "EV-BCB-02"] },
      { text: "Establish whether the fleet has been operating commercially since 30 April 2024 without a valid operator licence or national permit.", evidenceIds: ["EV-RTA-01", "EV-RTA-02", "EV-TRD-01"] },
      { text: "Obtain the purpose and funding of the eleven international trips, with priority on the flagged September 2024 departure.", evidenceIds: ["EV-IM-01", "EV-IM-02"] },
      { text: "Close out the overdue FY2022-23 filing and the unverified 2023 income certificate before any review is concluded.", evidenceIds: ["EV-IT-02", "EV-REV-02"] },
    ],
    riskLevel: "High",
    riskRationale: [
      { text: "Roughly ₹4.4 crore of asset acquisition is unexplained by declared income or recorded credit facilities.", evidenceIds: ["EV-IT-03", "EV-LR-02", "EV-LR-03"] },
      { text: "Core operating licence expired over a year ago while the fleet remains registered, cited and in use.", evidenceIds: ["EV-RTA-01", "EV-TRD-01", "EV-TRD-02"] },
      { text: "Statutory non-compliance recurs across four separate departments rather than appearing as an isolated lapse.", evidenceIds: ["EV-IT-02", "EV-RTA-02", "EV-TRD-03", "EV-GST-01"] },
      { text: "Travel behaviour is inconsistent with declared income, and one departure record is flagged.", evidenceIds: ["EV-IM-01", "EV-IM-02"] },
    ],
    recommendations: [
      { id: "REC-1", title: "Escalate for a joint financial records cross-check", detail: "Open a coordinated review between the Income Tax Department and the Land Records Department covering FY2021-25 to establish the source of funds behind the warehouse and land acquisitions. This is the single largest unexplained signal on the profile.", priority: "High", evidenceIds: ["EV-IT-03", "EV-LR-02", "EV-LR-03", "EV-BCB-02"] },
      { id: "REC-2", title: "Notify the Regional Transport Authority of active operation under an expired licence", detail: "The operator licence and national permit both expired in 2024, yet a fleet vehicle was challaned for permit violation in May 2024 and a second is running on an expired fitness certificate. Enforcement should be notified independently of the financial review.", priority: "High", evidenceIds: ["EV-RTA-01", "EV-RTA-02", "EV-TRD-01", "EV-TRD-02", "EV-TRD-03"] },
      { id: "REC-3", title: "Request an immigration review of the flagged departure", detail: "The 26 September 2024 departure to the UAE carries a flagged status that has not been resolved. Combined with eleven trips in five years against declared income, this warrants a formal request to the Bureau of Immigration.", priority: "High", evidenceIds: ["EV-IM-01", "EV-IM-02", "EV-IT-03"] },
      { id: "REC-4", title: "Suspend the PM Kisan disbursement pending the mutation outcome", detail: "Scheme eligibility rests on a landholding whose mutation is objected to before the Revenue Court. Disbursement should pause until the objection is decided.", priority: "Medium", evidenceIds: ["EV-REV-01", "EV-LR-03"] },
      { id: "REC-5", title: "Flag for manual review before any new licence, permit or scheme approval", detail: "Given open items across four departments, no new statutory approval should be granted to this citizen or the associated entities without officer review.", priority: "Medium", evidenceIds: ["EV-RTA-01", "EV-IT-02", "EV-GST-01", "EV-REV-02"] },
    ],
  },
};
