// Fully synthetic demonstration record. No real citizen, government, or
// department data is used — see /docs/07_SECURITY.md. Every AI-style claim is
// paired with evidence IDs so the UI can always render "why the system
// believes this."

import type { Citizen } from "../types";

export const ananyaRaoDeshmukh: Citizen = {
  citizenId: "NIR-CIT-100234",
  resolutionConfidence: 0.97,
  status: "Verified",
  quickSummary:
    "Pune-based technology professional. Three registered properties, two vehicles, consistent multi-year tax filings. One address proof pending verification.",
  linkedDepartments: [
    "Identity Authority",
    "Income Tax Department",
    "Land Records Department",
    "Transport Department",
    "Regional Passport Office",
    "Bureau of Immigration",
    "Municipal Corporation",
    "Banking & Credit Bureau",
    "Goods & Services Tax Network",
    "Welfare Department",
  ],

  identity: {
    fullName: "Ananya Rao Deshmukh",
    dateOfBirth: "1988-04-12",
    gender: "Female",
    aadhaar: "XXXX XXXX 4821",
    pan: "ARDPD4821Q",
    passport: "N8213457",
    drivingLicence: "MH12 20140091823",
    voterId: "MHX2841977",
    rationCard: "MH-PUN-2011-448210",
    abhaId: "24-8841-9023-4471",
    phone: "+91 98XXX XX341",
    email: "a.deshmukh@synthetic.example",
    photoInitials: "AD",
  },

  addressIntel: {
    geoConfidence: 0.94,
    current: {
      id: "ADR-100234-C",
      type: "Current",
      line: "Flat 12B, Silver Oak Residency, Baner Road",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
      fromDate: "2018-11-02",
      source: "Land Records Department",
      geoConfidence: 0.96,
    },
    permanent: {
      id: "ADR-100234-P",
      type: "Permanent",
      line: "Rao Nivas, Plot 9, Shivaji Nagar",
      city: "Nagpur",
      state: "Maharashtra",
      pincode: "440010",
      fromDate: "1988-04-12",
      source: "Identity Authority",
      geoConfidence: 0.91,
    },
    historical: [
      {
        id: "ADR-100234-H1",
        type: "Historical",
        line: "Flat 402, Sunrise Apartments, Kothrud",
        city: "Pune",
        state: "Maharashtra",
        pincode: "411038",
        fromDate: "2013-08-01",
        toDate: "2018-10-31",
        source: "Municipal Corporation",
        geoConfidence: 0.88,
      },
      {
        id: "ADR-100234-H2",
        type: "Historical",
        line: "Hostel Block C, University Campus, Ambazari",
        city: "Nagpur",
        state: "Maharashtra",
        pincode: "440033",
        fromDate: "2006-07-15",
        toDate: "2013-07-20",
        source: "Identity Authority",
        geoConfidence: 0.74,
      },
    ],
  },

  family: {
    householdId: "HH-PUN-411045-0912",
    members: [
      {
        id: "FAM-100234-1",
        name: "Rajesh Deshmukh",
        relation: "Spouse",
        age: 43,
        occupation: "Site Engineering Head",
        linkedCitizenId: "NIR-CIT-100235",
        verification: "Verified",
      },
      {
        id: "FAM-100234-2",
        name: "Meera Deshmukh",
        relation: "Daughter",
        age: 9,
        occupation: "Student",
        verification: "Verified",
      },
      {
        id: "FAM-100234-3",
        name: "Sunita Rao",
        relation: "Mother",
        age: 68,
        occupation: "Retired schoolteacher",
        verification: "Verified",
      },
      {
        id: "FAM-100234-4",
        name: "Madhav Rao",
        relation: "Father",
        age: 72,
        occupation: "Retired, State Electricity Board",
        verification: "Pending Verification",
      },
    ],
    emergencyContact: {
      name: "Rajesh Deshmukh",
      relation: "Spouse",
      phone: "+91 98XXX XX902",
    },
  },

  employment: {
    history: [
      {
        id: "EMP-100234-1",
        employer: "Kavach Analytics Pvt. Ltd.",
        role: "Senior Product Manager",
        sector: "Information Technology",
        since: "2019-06-01",
        status: "Active",
      },
      {
        id: "EMP-100234-2",
        employer: "Trident Consulting Group",
        role: "Business Analyst",
        sector: "Consulting",
        since: "2013-08-15",
        until: "2019-05-24",
        status: "Former",
      },
    ],
    gstRegistrations: [
      {
        gstin: "27ARDPD4821Q1ZK",
        legalName: "Deshmukh Retail Ventures",
        state: "Maharashtra",
        registeredOn: "2023-07-14",
        status: "Active",
        lastFiling: "2025-01-18",
      },
    ],
    directorships: [],
  },

  properties: [
    {
      id: "PROP-88213",
      category: "Residential",
      address: "Flat 12B, Silver Oak Residency, Baner Road, Pune",
      surveyOrUnitNo: "Unit 12B / CTS 448-A",
      areaSqFt: 1420,
      purchaseDate: "2018-10-18",
      registrationDate: "2018-11-02",
      declaredValue: 7400000,
      currentValuation: 9800000,
      ownershipShare: "50% joint with spouse",
      encumbrance: "Mortgaged",
      source: "Land Records Department",
      ownershipHistory: [
        { date: "2018-10-18", event: "Purchase agreement executed", detail: "Purchased from Silver Oak Developers Pvt. Ltd.", value: 7400000 },
        { date: "2018-11-02", event: "Registered", detail: "Sub-Registrar Haveli No. 4, Pune", value: 7400000 },
        { date: "2019-01-09", event: "Mortgage created", detail: "Home loan charge registered in favour of lender" },
      ],
    },
    {
      id: "PROP-91027",
      category: "Agricultural Land",
      address: "Survey No. 214, Mulshi Taluka, Pune District",
      surveyOrUnitNo: "Survey No. 214/2",
      areaSqFt: 43560,
      purchaseDate: "2021-12-28",
      registrationDate: "2022-01-19",
      declaredValue: 4200000,
      currentValuation: 5100000,
      ownershipShare: "100%",
      encumbrance: "Clear",
      source: "Land Records Department",
      ownershipHistory: [
        { date: "2021-12-28", event: "Sale deed executed", detail: "Acquired from local landholder", value: 4200000 },
        { date: "2022-01-19", event: "Registered", detail: "Sub-Registrar Mulshi", value: 4200000 },
        { date: "2022-03-04", event: "Mutation completed", detail: "Revenue records updated (7/12 extract)" },
      ],
    },
    {
      id: "PROP-93410",
      category: "Commercial",
      address: "Shop 4, Ganesh Arcade, FC Road, Pune",
      surveyOrUnitNo: "Shop Unit 4 / CTS 1129",
      areaSqFt: 620,
      purchaseDate: "2023-06-21",
      registrationDate: "2023-07-08",
      declaredValue: 6100000,
      currentValuation: 6600000,
      ownershipShare: "100%",
      encumbrance: "Clear",
      source: "Land Records Department",
      ownershipHistory: [
        { date: "2023-06-21", event: "Sale deed executed", detail: "Purchased from Ganesh Arcade Association", value: 6100000 },
        { date: "2023-07-08", event: "Registered", detail: "Sub-Registrar Shivajinagar, Pune", value: 6100000 },
      ],
    },
  ],

  vehicles: [
    {
      id: "VEH-55021",
      category: "Car",
      makeModel: "Honda City VX",
      registrationNumber: "MH12 GT 4471",
      registeredOn: "2020-02-14",
      fuel: "Petrol",
      insurance: {
        provider: "Sahyadri General Insurance",
        policyNumber: "SGI-MOT-4471-2024",
        validTill: "2025-02-13",
        status: "Active",
      },
      fitness: {
        certificateNumber: "FC-MH12-4471",
        validTill: "2035-02-13",
        status: "Valid",
      },
      challans: [
        { id: "CHL-9921", date: "2023-08-14", offence: "Over-speeding (68 in 50 zone)", location: "Baner Road, Pune", amount: 1000, status: "Paid" },
        { id: "CHL-10442", date: "2024-06-02", offence: "No-parking zone", location: "FC Road, Pune", amount: 500, status: "Paid" },
      ],
      ownershipHistory: [
        { date: "2020-02-14", event: "Registered", detail: "First owner registration, RTO Pune" },
      ],
    },
    {
      id: "VEH-55890",
      category: "Car",
      makeModel: "Hyundai Creta SX",
      registrationNumber: "MH14 BK 9021",
      registeredOn: "2023-09-30",
      fuel: "Diesel",
      insurance: {
        provider: "Deccan Assurance Ltd.",
        policyNumber: "DAL-MOT-9021-2024",
        validTill: "2025-09-29",
        status: "Active",
      },
      fitness: {
        certificateNumber: "FC-MH14-9021",
        validTill: "2038-09-29",
        status: "Valid",
      },
      challans: [],
      ownershipHistory: [
        { date: "2023-09-30", event: "Registered", detail: "First owner registration, RTO Pimpri-Chinchwad" },
      ],
    },
  ],

  financial: {
    incomeRange: "₹25,00,000 – ₹35,00,000 per annum",
    incomeTax: [
      { assessmentYear: "2024-25", declaredIncome: 3120000, taxPaid: 742000, filingStatus: "Filed", filedOn: "2024-07-19" },
      { assessmentYear: "2023-24", declaredIncome: 2680000, taxPaid: 601000, filingStatus: "Filed", filedOn: "2023-07-27" },
      { assessmentYear: "2022-23", declaredIncome: 1450000, taxPaid: 214000, filingStatus: "Filed", filedOn: "2022-07-30" },
    ],
    bankAccounts: [
      { id: "ACC-1", bank: "State Cooperative Bank", maskedNumber: "XXXXXXXX4471", type: "Savings", branch: "Baner, Pune", openedOn: "2013-09-02", status: "Active" },
      { id: "ACC-2", bank: "Deccan Commercial Bank", maskedNumber: "XXXXXXXX8830", type: "Current", branch: "FC Road, Pune", openedOn: "2023-07-20", status: "Active" },
      { id: "ACC-3", bank: "Nagpur Urban Bank", maskedNumber: "XXXXXXXX1109", type: "Savings", branch: "Shivaji Nagar, Nagpur", openedOn: "2006-08-11", status: "Dormant" },
    ],
    loans: [
      { id: "LON-1", lender: "State Cooperative Bank", type: "Home Loan", sanctionedAmount: 5200000, outstanding: 2840000, emi: 46800, sanctionedOn: "2019-01-09", status: "Active" },
      { id: "LON-2", lender: "Deccan Commercial Bank", type: "Vehicle Loan", sanctionedAmount: 1400000, outstanding: 0, emi: 0, sanctionedOn: "2020-02-10", status: "Closed" },
    ],
    creditProfile: { score: 786, bureau: "National Credit Bureau", band: "Excellent", asOf: "2025-01-31" },
    mutualFunds: [
      { id: "MF-1", kind: "Mutual Fund", institution: "Sahyadri Asset Management", identifier: "FOLIO-88420117", value: 1240000, startedOn: "2017-04-11" },
      { id: "MF-2", kind: "Mutual Fund", institution: "Deccan Mutual", identifier: "FOLIO-55190283", value: 480000, startedOn: "2021-06-02" },
    ],
    fixedDeposits: [
      { id: "FD-1", kind: "Fixed Deposit", institution: "State Cooperative Bank", identifier: "FD-4471-0091", value: 800000, startedOn: "2022-11-15", maturityOn: "2025-11-15" },
    ],
    insurance: [
      { id: "INS-1", insurer: "Bharat Life Assurance", type: "Life", policyNumber: "BLA-9920-4471", sumAssured: 10000000, annualPremium: 62000, validTill: "2048-03-31", status: "Active" },
      { id: "INS-2", insurer: "Sahyadri General Insurance", type: "Health", policyNumber: "SGI-HLT-4471", sumAssured: 1500000, annualPremium: 28000, validTill: "2025-06-30", status: "Active" },
    ],
    upiIds: [
      { handle: "ananya.d@synthbank", linkedBank: "State Cooperative Bank", status: "Active" },
      { handle: "deshmukhretail@synthpay", linkedBank: "Deccan Commercial Bank", status: "Active" },
    ],
  },

  travel: {
    passport: {
      number: "N8213457",
      issueDate: "2021-03-11",
      expiryDate: "2031-03-10",
      issuingOffice: "Regional Passport Office, Pune",
      status: "Active",
    },
    trips: [
      { id: "TRP-1", country: "Singapore", flag: "🇸🇬", purpose: "Business", visaType: "Business (30 days)", exitDate: "2018-05-06", entryDate: "2018-05-11", durationDays: 5, port: "Mumbai (BOM)" },
      { id: "TRP-2", country: "United Arab Emirates", flag: "🇦🇪", purpose: "Tourism", visaType: "Visit (30 days)", exitDate: "2019-11-02", entryDate: "2019-11-09", durationDays: 7, port: "Mumbai (BOM)" },
      { id: "TRP-3", country: "Thailand", flag: "🇹🇭", purpose: "Tourism", visaType: "Visa on Arrival", exitDate: "2022-02-18", entryDate: "2022-02-22", durationDays: 4, port: "Pune (PNQ)" },
      { id: "TRP-4", country: "United Kingdom", flag: "🇬🇧", purpose: "Conference", visaType: "Standard Visitor", exitDate: "2023-04-15", entryDate: "2023-04-24", durationDays: 9, port: "Mumbai (BOM)" },
      { id: "TRP-5", country: "Singapore", flag: "🇸🇬", purpose: "Business", visaType: "Business (30 days)", exitDate: "2023-10-07", entryDate: "2023-10-13", durationDays: 6, port: "Mumbai (BOM)" },
      { id: "TRP-6", country: "Germany", flag: "🇩🇪", purpose: "Business", visaType: "Schengen Type C", exitDate: "2024-03-09", entryDate: "2024-03-17", durationDays: 8, port: "Mumbai (BOM)" },
      { id: "TRP-7", country: "Sri Lanka", flag: "🇱🇰", purpose: "Family", visaType: "ETA (30 days)", exitDate: "2024-12-21", entryDate: "2024-12-25", durationDays: 4, port: "Pune (PNQ)" },
    ],
    immigrationRecords: [
      { id: "IMM-1", date: "2024-12-25", type: "Arrival", port: "Pune (PNQ)", reference: "BOI/ARR/2024/884210", status: "Cleared" },
      { id: "IMM-2", date: "2024-12-21", type: "Departure", port: "Pune (PNQ)", reference: "BOI/DEP/2024/884109", status: "Cleared" },
      { id: "IMM-3", date: "2024-03-17", type: "Arrival", port: "Mumbai (BOM)", reference: "BOI/ARR/2024/551027", status: "Cleared" },
      { id: "IMM-4", date: "2024-03-09", type: "Departure", port: "Mumbai (BOM)", reference: "BOI/DEP/2024/550918", status: "Cleared" },
    ],
    totalTrips: 7,
    countriesVisited: 6,
    averageStayDays: 6.1,
    travelFrequency: "≈1 trip per year over 7 years",
    lastExit: "2024-12-21",
    lastEntry: "2024-12-25",
    observation: {
      text: "Citizen travelled internationally 7 times across 6 countries with an average stay of 6.1 days. Trip purposes align with the declared technology-sector role, and no immigration anomalies are recorded.",
      evidenceIds: ["EV-PP-01", "EV-IM-01", "EV-EMP-01"],
    },
  },

  benefits: [
    {
      id: "BEN-30044",
      scheme: "Pradhan Mantri Fasal Bima Yojana",
      category: "Agriculture",
      department: "Welfare Department",
      enrollmentDate: "2022-05-01",
      status: "Inactive",
      eligibility: "Under Review",
      amountDisbursed: 0,
    },
    { id: "BEN-30045", scheme: "Pradhan Mantri Awas Yojana", category: "Housing", department: "Welfare Department", status: "Not Enrolled", eligibility: "Not Eligible" },
    { id: "BEN-30046", scheme: "Ayushman Bharat", category: "Health", department: "Health Authority", status: "Not Enrolled", eligibility: "Not Eligible" },
    { id: "BEN-30047", scheme: "National Scholarship Portal", category: "Education", department: "Welfare Department", status: "Not Enrolled", eligibility: "Not Eligible" },
    { id: "BEN-30048", scheme: "National Pension Scheme", category: "Pension", department: "Welfare Department", enrollmentDate: "2020-04-15", status: "Active", eligibility: "Eligible", amountDisbursed: 0, lastDisbursedOn: undefined },
    { id: "BEN-30049", scheme: "Direct Benefit Transfer (LPG Subsidy)", category: "DBT", department: "Welfare Department", enrollmentDate: "2016-08-09", status: "Inactive", eligibility: "Not Eligible", amountDisbursed: 4812, lastDisbursedOn: "2021-03-11" },
  ],

  documents: [
    { id: "DOC-70010", type: "Aadhaar", documentNumber: "XXXX XXXX 4821", issuingAuthority: "Identity Authority", issueDate: "2011-06-22", status: "Verified", verificationConfidence: 0.99 },
    { id: "DOC-70011", type: "Passport", documentNumber: "N8213457", issuingAuthority: "Regional Passport Office, Pune", issueDate: "2021-03-11", expiryDate: "2031-03-10", status: "Verified", verificationConfidence: 0.98 },
    { id: "DOC-70012", type: "Income Certificate", documentNumber: "REV/PUN/2024/88213", issuingAuthority: "Revenue Department", issueDate: "2024-04-01", expiryDate: "2025-03-31", status: "Verified", verificationConfidence: 0.93 },
    { id: "DOC-70013", type: "Address Proof", documentNumber: "PMC/AP/2022/44120", issuingAuthority: "Municipal Corporation", issueDate: "2022-08-19", status: "Pending Verification", verificationConfidence: 0.46 },
    { id: "DOC-70014", type: "PAN Card", documentNumber: "ARDPD4821Q", issuingAuthority: "Income Tax Department", issueDate: "2009-02-17", status: "Verified", verificationConfidence: 0.99 },
    { id: "DOC-70015", type: "Voter ID", documentNumber: "MHX2841977", issuingAuthority: "Election Commission", issueDate: "2010-01-25", status: "Verified", verificationConfidence: 0.95 },
  ],

  licences: [
    { id: "LIC-40091", type: "Driving Licence (LMV + MCWG)", category: "Driving", licenceNumber: "MH12 20140091823", issuingAuthority: "Regional Transport Office, Pune", issueDate: "2014-01-09", expiryDate: "2034-01-08", status: "Active" },
    { id: "LIC-40092", type: "Shop & Establishment Licence", category: "Business", licenceNumber: "PMC/SE/2023/40092", issuingAuthority: "Municipal Corporation", issueDate: "2023-07-10", expiryDate: "2025-07-09", status: "Active" },
    { id: "LIC-40093", type: "Certified Product Manager (Professional)", category: "Professional", licenceNumber: "CPM-IN-2019-3341", issuingAuthority: "Employment Records", issueDate: "2019-09-01", expiryDate: "2027-08-31", status: "Active" },
  ],

  timeline: [
    { date: "2009-02-17", title: "PAN issued", description: "Permanent Account Number allotted by the Income Tax Department.", department: "Income Tax Department", category: "Identity", evidenceIds: ["EV-ID-01"] },
    { date: "2011-06-22", title: "Aadhaar enrolment completed", description: "Biometric identity record created and verified.", department: "Identity Authority", category: "Identity", evidenceIds: ["EV-ID-01"] },
    { date: "2013-08-15", title: "First employment recorded", description: "Joined Trident Consulting Group as Business Analyst.", department: "Employment Records", category: "Employment", evidenceIds: ["EV-EMP-02"] },
    { date: "2014-01-09", title: "Driving licence issued", description: "LMV and MCWG driving licence issued.", department: "Regional Transport Office", category: "Licence", evidenceIds: ["EV-TR-03"] },
    { date: "2018-05-06", title: "First international travel", description: "Business travel to Singapore; cleared immigration on both legs.", department: "Bureau of Immigration", category: "Travel", evidenceIds: ["EV-IM-01"] },
    { date: "2018-11-02", title: "Residential property registered", description: "Primary residence registered jointly with spouse.", department: "Land Records Department", category: "Property", evidenceIds: ["EV-LR-01"] },
    { date: "2019-06-01", title: "Employment change", description: "Joined Kavach Analytics Pvt. Ltd. as Senior Product Manager.", department: "Employment Records", category: "Employment", evidenceIds: ["EV-EMP-01"] },
    { date: "2020-02-14", title: "Vehicle registered", description: "Honda City registered as first owner.", department: "Transport Department", category: "Vehicle", evidenceIds: ["EV-TR-01"] },
    { date: "2021-03-11", title: "Passport issued", description: "Passport renewed and verified by the Regional Passport Office.", department: "Regional Passport Office", category: "Travel", evidenceIds: ["EV-PP-01"] },
    { date: "2022-01-19", title: "Agricultural land registered", description: "Land parcel registered in Mulshi Taluka.", department: "Land Records Department", category: "Property", evidenceIds: ["EV-LR-02"] },
    { date: "2022-08-19", title: "Address proof issued", description: "Municipal address proof issued; verification still pending.", department: "Municipal Corporation", category: "Identity", evidenceIds: ["EV-MUN-01"] },
    { date: "2023-07-08", title: "Commercial property registered", description: "Shop unit purchased on FC Road, Pune.", department: "Land Records Department", category: "Property", evidenceIds: ["EV-LR-03"] },
    { date: "2023-07-14", title: "GST registration granted", description: "Deshmukh Retail Ventures registered under GST.", department: "Goods & Services Tax Network", category: "Employment", evidenceIds: ["EV-GST-01"] },
    { date: "2023-09-30", title: "Second vehicle registered", description: "Hyundai Creta registered as first owner.", department: "Transport Department", category: "Vehicle", evidenceIds: ["EV-TR-02"] },
    { date: "2024-07-19", title: "Income tax return filed", description: "AY 2024-25 return filed declaring ₹31,20,000.", department: "Income Tax Department", category: "Financial", evidenceIds: ["EV-IT-01"] },
    { date: "2024-12-25", title: "Returned from international travel", description: "Arrival from Sri Lanka cleared at Pune.", department: "Bureau of Immigration", category: "Travel", evidenceIds: ["EV-IM-01"] },
  ],

  evidence: [
    { id: "EV-ID-01", label: "Core identity record with linked PAN and Aadhaar", sourceDepartment: "Identity Authority", sourceRecordId: "NIR-CIT-100234", referenceNumber: "IDA/PUN/2011/4821", confidence: 0.99, verificationStatus: "Verified", linkedRecord: "Identity → Aadhaar, PAN", recordedOn: "2024-11-02" },
    { id: "EV-IT-01", label: "Income tax return, AY 2024-25 — declared income ₹31,20,000", sourceDepartment: "Income Tax Department", sourceRecordId: "IT-2024-25-3120000", referenceNumber: "ITD/ITR/2024/8842107", confidence: 0.97, verificationStatus: "Verified", linkedRecord: "Financial → Income tax", recordedOn: "2024-07-19" },
    { id: "EV-IT-02", label: "Three-year filing history with no lapses", sourceDepartment: "Income Tax Department", sourceRecordId: "IT-2022-2025-history", referenceNumber: "ITD/HIST/100234", confidence: 0.96, verificationStatus: "Verified", linkedRecord: "Financial → Income tax", recordedOn: "2024-07-19" },
    { id: "EV-LR-01", label: "Residential property registration, jointly held", sourceDepartment: "Land Records Department", sourceRecordId: "PROP-88213", referenceNumber: "LRD/HAV4/2018/88213", confidence: 0.98, verificationStatus: "Verified", linkedRecord: "Property → PROP-88213", recordedOn: "2018-11-02" },
    { id: "EV-LR-02", label: "Agricultural land registration and completed mutation", sourceDepartment: "Land Records Department", sourceRecordId: "PROP-91027", referenceNumber: "LRD/MUL/2022/91027", confidence: 0.95, verificationStatus: "Verified", linkedRecord: "Property → PROP-91027", recordedOn: "2022-03-04" },
    { id: "EV-LR-03", label: "Commercial property registration, FC Road", sourceDepartment: "Land Records Department", sourceRecordId: "PROP-93410", referenceNumber: "LRD/SHV/2023/93410", confidence: 0.96, verificationStatus: "Verified", linkedRecord: "Property → PROP-93410", recordedOn: "2023-07-08" },
    { id: "EV-TR-01", label: "Vehicle registration — Honda City (MH12 GT 4471)", sourceDepartment: "Transport Department", sourceRecordId: "VEH-55021", referenceNumber: "TRD/PUN/2020/55021", confidence: 0.97, verificationStatus: "Verified", linkedRecord: "Vehicle → VEH-55021", recordedOn: "2020-02-14" },
    { id: "EV-TR-02", label: "Vehicle registration — Hyundai Creta (MH14 BK 9021)", sourceDepartment: "Transport Department", sourceRecordId: "VEH-55890", referenceNumber: "TRD/PCM/2023/55890", confidence: 0.97, verificationStatus: "Verified", linkedRecord: "Vehicle → VEH-55890", recordedOn: "2023-09-30" },
    { id: "EV-TR-03", label: "Driving licence, valid to 2034", sourceDepartment: "Regional Transport Authority", sourceRecordId: "LIC-40091", referenceNumber: "RTA/PUN/2014/91823", confidence: 0.98, verificationStatus: "Verified", linkedRecord: "Licence → LIC-40091", recordedOn: "2014-01-09" },
    { id: "EV-PP-01", label: "Passport record, active to 2031", sourceDepartment: "Regional Passport Office", sourceRecordId: "DOC-70011", referenceNumber: "RPO/PUN/2021/8213457", confidence: 0.98, verificationStatus: "Verified", linkedRecord: "Travel → Passport", recordedOn: "2021-03-11" },
    { id: "EV-IM-01", label: "Immigration history — 7 trips, all clearances recorded", sourceDepartment: "Bureau of Immigration", sourceRecordId: "IMM-100234-ALL", referenceNumber: "BOI/HIST/100234", confidence: 0.94, verificationStatus: "Verified", linkedRecord: "Travel → Immigration records", recordedOn: "2024-12-25" },
    { id: "EV-MUN-01", label: "Municipal address proof awaiting field verification", sourceDepartment: "Municipal Corporation", sourceRecordId: "DOC-70013", referenceNumber: "PMC/AP/2022/44120", confidence: 0.46, verificationStatus: "Pending Verification", linkedRecord: "Document → DOC-70013", recordedOn: "2022-08-19" },
    { id: "EV-ADR-01", label: "Residential address corroborated by three independent departments", sourceDepartment: "Identity Authority", sourceRecordId: "ADR-100234-C", referenceNumber: "IDA/ADR/100234", confidence: 0.96, verificationStatus: "Verified", linkedRecord: "Address → Current", recordedOn: "2024-11-02" },
    { id: "EV-FAM-01", label: "Spouse identity linkage within the same household record", sourceDepartment: "Identity Authority", sourceRecordId: "NIR-CIT-100235", referenceNumber: "IDA/HH/411045/0912", confidence: 0.95, verificationStatus: "Verified", linkedRecord: "Family → Spouse", recordedOn: "2024-11-02" },
    { id: "EV-EMP-01", label: "Active employment record, technology sector", sourceDepartment: "Employment Records", sourceRecordId: "EMP-100234-1", referenceNumber: "EMP/KAV/2019/1188", confidence: 0.93, verificationStatus: "Verified", linkedRecord: "Employment → Current", recordedOn: "2024-10-01" },
    { id: "EV-EMP-02", label: "Prior employment record, consulting sector", sourceDepartment: "Employment Records", sourceRecordId: "EMP-100234-2", referenceNumber: "EMP/TCG/2013/0447", confidence: 0.89, verificationStatus: "Verified", linkedRecord: "Employment → History", recordedOn: "2019-05-24" },
    { id: "EV-GST-01", label: "Active GST registration with current filings", sourceDepartment: "Goods & Services Tax Network", sourceRecordId: "27ARDPD4821Q1ZK", referenceNumber: "GST/MH/2023/4821Q", confidence: 0.94, verificationStatus: "Verified", linkedRecord: "Employment → GST", recordedOn: "2025-01-18" },
    { id: "EV-BCB-01", label: "Credit profile — score 786, no irregular accounts", sourceDepartment: "Banking & Credit Bureau", sourceRecordId: "CB-100234", referenceNumber: "BCB/RPT/2025/100234", confidence: 0.92, verificationStatus: "Verified", linkedRecord: "Financial → Credit profile", recordedOn: "2025-01-31" },
    { id: "EV-BCB-02", label: "Home loan outstanding ₹28,40,000, servicing regular", sourceDepartment: "Banking & Credit Bureau", sourceRecordId: "LON-1", referenceNumber: "BCB/LON/2019/5200", confidence: 0.91, verificationStatus: "Verified", linkedRecord: "Financial → Loans", recordedOn: "2025-01-31" },
    { id: "EV-WFD-01", label: "Inactive welfare scheme enrolment (PMFBY)", sourceDepartment: "Welfare Department", sourceRecordId: "BEN-30044", referenceNumber: "WFD/PMFBY/2022/30044", confidence: 0.88, verificationStatus: "Verified", linkedRecord: "Benefit → BEN-30044", recordedOn: "2022-05-01" },
  ],

  aiSummary: {
    metrics: {
      aiConfidence: 0.97,
      departmentsCorrelated: 10,
      recordsAnalysed: 64,
      evidenceSources: 20,
      documentsLinked: 6,
      riskScore: 18,
      citizenStatus: "Verified",
    },
    executiveSummary:
      "Ananya Rao Deshmukh is a 36-year-old technology professional resident in Pune, resolved across ten departments at 97% confidence. Asset holdings, declared income and credit behaviour are mutually consistent, and international travel matches the declared professional profile. One administrative item is outstanding: a municipal address proof issued in 2022 that has never completed field verification. No investigative escalation is indicated.",
    domainSummaries: [
      { key: "identity", title: "Identity Summary", text: "All eleven identity attributes are populated and corroborated by at least two departments each. Aadhaar, PAN, passport and voter records agree on name and date of birth with no variant spellings across sources.", evidenceIds: ["EV-ID-01", "EV-PP-01", "EV-ADR-01"] },
      { key: "income", title: "Income Summary", text: "Declared income rose from ₹14,50,000 to ₹31,20,000 across three assessment years, each filed on time. Credit score of 786 and a regularly serviced home loan corroborate the declared earning band.", evidenceIds: ["EV-IT-01", "EV-IT-02", "EV-BCB-01", "EV-BCB-02"] },
      { key: "property", title: "Property Summary", text: "Three registered properties with a combined current valuation of ₹2,15,00,000. Acquisitions are spread over five years and sit within the cumulative declared income and sanctioned loan capacity for the period. No encumbrance disputes are on record.", evidenceIds: ["EV-LR-01", "EV-LR-02", "EV-LR-03", "EV-BCB-02"] },
      { key: "travel", title: "Travel Summary", text: "Seven international trips across six countries since 2018, averaging 6.1 days. Purposes are predominantly business and conference travel consistent with the employment record. All immigration clearances are recorded with no flags.", evidenceIds: ["EV-PP-01", "EV-IM-01", "EV-EMP-01"] },
      { key: "employment", title: "Employment Summary", text: "Continuous employment since 2013 with a single sector transition in 2019. One active GST registration tied to the commercial property, filing up to date. No corporate directorships on record.", evidenceIds: ["EV-EMP-01", "EV-EMP-02", "EV-GST-01"] },
      { key: "behaviour", title: "Behaviour Summary", text: "Filing, licensing and repayment behaviour is consistently on time across all departments. Two minor traffic challans since 2020, both paid. No pattern of lapsed renewals or missed statutory deadlines.", evidenceIds: ["EV-IT-02", "EV-TR-01", "EV-BCB-01"] },
      { key: "risk", title: "Risk Summary", text: "Risk score 18/100 (Low). The single open item is the unverified municipal address proof, which is administrative and does not conflict with any other department's address record.", evidenceIds: ["EV-MUN-01", "EV-ADR-01"] },
    ],
    inconsistencies: [
      { text: "Address proof on file has not completed verification, while the same address is independently corroborated by the Land Records Department and the Identity Authority.", evidenceIds: ["EV-MUN-01", "EV-ADR-01"] },
      { text: "Commercial property (₹61,00,000) was acquired in the same assessment year as a declared income of ₹31,20,000 — plausible given prior years' income and closed vehicle loan, but the financing source is not recorded on file.", evidenceIds: ["EV-IT-01", "EV-LR-03", "EV-BCB-02"] },
    ],
    schemeEligibility: [
      { text: "Not eligible for income-linked welfare schemes (PMAY, Ayushman Bharat, scholarships) — declared income exceeds every applicable threshold.", evidenceIds: ["EV-IT-01"] },
      { text: "Existing PMFBY enrolment is Inactive against a landholding that remains registered; eligibility is marked Under Review and may warrant closure or reinstatement.", evidenceIds: ["EV-WFD-01", "EV-LR-02"] },
    ],
    linkedEntities: [
      { text: "Spouse Rajesh Deshmukh resolves to an existing citizen record (NIR-CIT-100235) sharing household ID, residential address and one vehicle registration.", evidenceIds: ["EV-FAM-01", "EV-ADR-01", "EV-TR-01"] },
      { text: "Business entity 'Deshmukh Retail Ventures' (GSTIN 27ARDPD4821Q1ZK) is registered at the commercial property address held by this citizen.", evidenceIds: ["EV-GST-01", "EV-LR-03"] },
    ],
    investigationLeads: [
      { text: "Complete field verification of the municipal address proof to close the only open item on this profile.", evidenceIds: ["EV-MUN-01"] },
      { text: "If a financial inquiry is opened for unrelated reasons, reconcile commercial property financing against the FY2022-23 and FY2023-24 income record.", evidenceIds: ["EV-IT-01", "EV-LR-03"] },
    ],
    riskLevel: "Low",
    riskRationale: [
      { text: "No open legal records, no expired or revoked licences, and an unbroken three-year tax filing history.", evidenceIds: ["EV-IT-02", "EV-TR-03"] },
      { text: "Asset acquisition is proportionate to declared income once the sanctioned home loan is accounted for.", evidenceIds: ["EV-BCB-02", "EV-LR-01"] },
      { text: "The single unresolved verification is administrative and contradicted by no other department record.", evidenceIds: ["EV-MUN-01", "EV-ADR-01"] },
    ],
    recommendations: [
      { id: "REC-1", title: "Route address proof to the verification queue", detail: "The 2022 municipal address proof should not be relied on as a standalone document until field verification completes. Two other departments already corroborate the address, so this is a records-hygiene action rather than an investigative one.", priority: "Medium", evidenceIds: ["EV-MUN-01", "EV-ADR-01"] },
      { id: "REC-2", title: "Review the inactive PMFBY enrolment", detail: "Scheme enrolment is Inactive while the underlying agricultural landholding remains registered. Refer to the Welfare Department to either close the enrolment or restore it.", priority: "Low", evidenceIds: ["EV-WFD-01", "EV-LR-02"] },
      { id: "REC-3", title: "No investigative escalation warranted", detail: "Across ten correlated departments no contradiction, lapse or unexplained asset was identified. Recommend closing the review with no further action.", priority: "Low", evidenceIds: ["EV-IT-02", "EV-BCB-01", "EV-IM-01"] },
    ],
  },
};
