import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowUpRight, FileX2, MonitorPlay } from "lucide-react";
import { useReport } from "@/lib/reports/store";
import { renderReportHtml } from "@/lib/reports/render-html";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import { EmptyState } from "@/components/ui/EmptyState";
import { RiskBadge } from "@/components/ui/RiskBadge";
import { DataRow } from "@/components/ui/DataRow";
import { ExportButtons } from "@/components/reports/ExportButtons";
import { formatDateTime } from "@/lib/format";

const LOAD_DELAY_MS = 240;

export function ReportDetailPage() {
  const { reportId } = useParams<{ reportId: string }>();
  const report = useReport(reportId);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    window.scrollTo({ top: 0 });
    const timer = setTimeout(() => setLoading(false), LOAD_DELAY_MS);
    return () => clearTimeout(timer);
  }, [reportId]);

  // The preview is the exact document that HTML export downloads and PDF prints.
  const previewHtml = useMemo(
    () => (report ? renderReportHtml(report.document) : ""),
    [report],
  );

  if (loading) {
    return (
      <div className="mx-auto max-w-5xl px-6 py-8">
        <Skeleton className="h-4 w-32" />
        <div className="mt-4 flex flex-col gap-6" aria-busy="true">
          <Skeleton className="h-44 rounded-2xl" />
          <Skeleton className="h-[600px] rounded-2xl" />
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="mx-auto max-w-3xl px-6 py-16">
        <EmptyState
          icon={<FileX2 size={22} strokeWidth={2} />}
          title="Report not found"
          description={`No saved report matches ID “${reportId}”. Reports are stored in this browser only.`}
        />
        <div className="flex justify-center">
          <Link
            to="/reports"
            className="rounded-lg text-sm font-semibold text-primary-700 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-400"
          >
            Back to reports
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl px-6 py-8">
      <Link
        to="/reports"
        className="mb-4 inline-flex items-center gap-1.5 rounded text-sm font-medium text-ink-500 transition-colors hover:text-ink-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-400"
      >
        <ArrowLeft size={15} aria-hidden="true" /> Back to reports
      </Link>

      <div className="flex flex-col gap-6">
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
        >
          <Card className="p-6">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div className="min-w-0 flex-1 basis-64">
                <div className="flex flex-wrap items-center gap-2">
                  <h1 className="font-mono text-lg font-bold text-ink-900">{report.id}</h1>
                  {report.investigationId ? (
                    <Badge variant="primary">Case {report.investigationId}</Badge>
                  ) : (
                    <Badge variant="neutral">Standalone</Badge>
                  )}
                  {report.caseStatus && <Badge variant="accent">{report.caseStatus}</Badge>}
                </div>
                <p className="mt-1 text-sm font-semibold text-ink-900">{report.citizenName}</p>
                <Link
                  to={`/citizens/${report.citizenId}`}
                  className="inline-flex items-center gap-0.5 rounded font-mono text-xs font-medium text-primary-700 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-400"
                >
                  {report.citizenId}
                  <ArrowUpRight size={11} strokeWidth={2.5} aria-hidden="true" />
                </Link>
              </div>

              <RiskBadge level={report.riskLevel} className="shrink-0" />
            </div>

            <div className="mt-4 grid gap-x-8 border-t border-ink-100 pt-3 sm:grid-cols-2">
              <DataRow label="Generated by" value={report.officer} />
              <DataRow label="Generated at" value={formatDateTime(report.generatedAt)} />
              <DataRow label="Risk score" value={`${report.riskScore}/100`} />
              <DataRow label="Exports taken" value={String(report.exports.length)} />
            </div>

            <div className="mt-4 border-t border-ink-100 pt-4">
              <p className="mb-2 font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-400">
                Download
              </p>
              <ExportButtons report={report} />
            </div>

            {report.exports.length > 0 && (
              <div className="mt-4 border-t border-ink-100 pt-3">
                <p className="mb-2 font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-400">
                  Export history
                </p>
                <ul className="flex flex-wrap gap-2">
                  {report.exports.slice(0, 8).map((event) => (
                    <li
                      key={event.id}
                      className="rounded-lg border border-ink-200 bg-canvas/60 px-2.5 py-1 text-[11px] text-ink-600"
                    >
                      <span className="font-semibold text-ink-900">{event.format}</span> ·{" "}
                      {formatDateTime(event.at)}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </Card>
        </motion.div>

        <Card className="overflow-hidden">
          <div className="flex items-center gap-3.5 border-b border-ink-100 px-5 py-4">
            <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary-600 text-white">
              <MonitorPlay size={18} aria-hidden="true" />
            </span>
            <div>
              <h2 className="font-semibold text-ink-900">Report Preview</h2>
              <p className="text-sm text-ink-500">
                Exactly what HTML export downloads and PDF export prints
              </p>
            </div>
          </div>

          <iframe
            title={`Preview of report ${report.id}`}
            srcDoc={previewHtml}
            className="h-[720px] w-full border-0 bg-canvas"
          />
        </Card>
      </div>
    </div>
  );
}
